#!/bin/bash

color_default="\033[0m"
fg_blue="\033[0;36m"
fg_green="\033[0;32m"
fg_orange="\033[0;33m"
fg_red="\033[0;31m"
function log_error  { >&2 echo -e "${fg_red}$1${color_default}"; }
function log_info { >&2 echo -e "${fg_blue}$1${color_default}"; }
function log_success { >&2 echo -e "${fg_green}$1${color_default}"; }
function log_warning { >&2 echo -e "${fg_orange}$1${color_default}"; }

script_name="$(basename ${BASH_SOURCE[0]})"
script_reldir="$(dirname ${BASH_SOURCE[0]})"
script_absdir="$(cd $script_reldir > /dev/null && pwd)"

trap_error () {
	exit_code=$?
	failed_cmd="$BASH_COMMAND"
	failed_line_nr="$BASH_LINENO"
	log_error ">>> Failed the execution of $script_name on line $failed_line_nr."
	log_error ">>> Command '$failed_cmd' failed with exit code $exit_code."
}

trap_exit () {
	popd >/dev/null
}

trap_user_exit () {
	[ -n "$(docker ps -q --filter name="$container")" ] &&
		log_info ">>> Stopping $container ..." &&
		docker stop "$container" &&
		log_info ">>> Stopped $container" &&
		exit 0
}

set -e
trap trap_error ERR
trap trap_exit EXIT
trap trap_user_exit INT

pushd "$script_absdir" >/dev/null

# Other RMQ images can be found at https://hub.docker.com/_/rabbitmq
# ATM there's no arm64/v8 version available for the alpine flavor.
arch="${ARCH:-$(uname -m)}"
container=""
platform=""
tag=""
version="${VERSION:-3.11.18}"
volume="psevdaisthisi-rmq"

env_port1=5672
env_port2=15672

if [ "$arch" == "arm64" ]; then
	platform="linux/arm64/v8"
	container="psevdaisthisi-rmq-arm64-$version"
	tag="rabbitmq:$version-management"

elif [ "$arch" == "x86_64" ]; then
	platform="linux/x86_64"
	container="psevdaisthisi-rmq-arm64-$version"
	tag="rabbitmq:$version-alpine-management"

else
	log_error ">>> Unsupported architecture: $arch."
	exit 1
fi

if [ "$1" == "build" ]; then
	docker volume create "$volume"

elif [ "$1" == "reset" ]; then
	docker rm "$container" || true
	docker volume rm "$volume" || true

elif [ "$1" == "rm" ]; then
	docker rm "$container" || true
	docker volume rm "$volume" || true
	docker rmi "$tag" || true

elif [ "$1" == "run" ]; then
	already_ran=$(docker ps -aq --filter name="$container")
	[ -n "$already_ran" ] && docker start "$container"

	[ -z "$already_ran" ] && docker run -d --init \
		-p "$env_port1:$env_port1" \
		-p "$env_port2:$env_port2" \
		--mount source="$volume",target=/usr/local/rabbitmq/var/lib/rabbitmq/mnesia \
		--mount type=tmpfs,destination=/usr/local/rabbitmq/var/log/rabbitmq \
		--name "$container" \
		"$tag"

	docker logs --follow --tail 15 "$container" &
	wait

elif [ "$1" == "stop" ]; then
	[ -n "$(docker ps -q --filter name="$container")" ] &&
		docker stop "$container" &&
		log_info ">>> Stopped $container"

else
	log_warning ">>> Unknown or missing action."
	log_warning "$ ./do build|run|stop|reset|rm"
fi