#!/bin/bash

script_name="$(basename ${BASH_SOURCE[0]})"
script_reldir="$(dirname ${BASH_SOURCE[0]})"
script_absdir="$(cd $script_reldir > /dev/null && pwd)"
. "$script_absdir"/../misc.sh

set -e
trap trap_error ERR
trap trap_exit EXIT
trap trap_user_exit INT


pushd "$script_absdir" >/dev/null

arch="${ARCH:-$(uname -m)}"
container=""
platform=""
prefix="${PREFIX:-gh}"
tag=""
volume="${prefix}-mssql"

env_port=1433

# Other SQL Server images can be found at:
# arm64  -> https://mcr.microsoft.com/v2/azure-sql-edge/tags/list
# x86_64 -> https://hub.docker.com/_/microsoft-mssql-server
if [ "$arch" == "arm64" ]; then
	platform="linux/arm64/v8"
	version="${VERSION:-1.0.7}"
	container="${prefix}-mssql-arm64-$version"
	tag="mcr.microsoft.com/azure-sql-edge:${version}"

elif [ "$arch" == "x86_64" ]; then
	platform="linux/x86_64"
	container="${prefix}-rmq-arm64-$version"
	version="${VERSION:-2019-CU20-ubuntu-20.04}"
	tag="mcr.microsoft.com/mssql/server:$version"

else
	log_error ">>> Unsupported architecture: $arch."
	exit 1
fi

if [ "$1" == "build" ]; then
	docker volume create "$volume"

elif [ "$1" == "reset" ]; then
	container_reset "$container" "$volume"

elif [ "$1" == "rm" ]; then
	container_rm "$container" "$volume" "$tag"

elif [ "$1" == "run" ]; then
	already_ran=$(docker ps -aq --filter name="$container")
	[ -n "$already_ran" ] && docker start "$container"

	[ -z "$already_ran" ] && docker run -d --init \
		-p "$env_port:$env_port" \
		-e ACCEPT_EULA=Y \
		-e MSSQL_PID=Developer \
		-e MSSQL_SA_PASSWORD="mssql!42" \
		-e MSSQL_TELEMETRY_ENABLED=FALSE \
		--platform $platform \
		--mount source="$volume",target=/var/opt/mssql \
		--name "$container" \
		"$tag"

	docker logs --follow --tail 15 "$container" &
	wait

elif [ "$1" == "stop" ]; then
	container_stop "$container"

else
	log_warning ">>> Unknown or missing action."
	log_warning "$ ./do build|run|stop|reset|rm"
fi