#!/bin/bash

script_name="$(basename ${BASH_SOURCE[0]})"
script_reldir="$(dirname ${BASH_SOURCE[0]})"
script_absdir="$(cd $script_reldir > /dev/null && pwd)"
. "$script_absdir"/../misc.sh

set -e
trap trap_error ERR
trap trap_exit EXIT
trap trap_user_exit INT

pushd "$script_absdir" >/dev/null

# MongoDB releases are listed at
# https://github.com/mongodb/mongo/tags
action="$1"
arch="${ARCH:-$(uname -m)}"
container=""
platform=""
prefix="${PREFIX:-gh}"
tag=""
version_mongo="${version_mongo:-7.0.7}"
version_mongosh="${version_mongosh:-2.2.0}"
volume="${prefix}-mongo"
arg_pkg_mongo="https://fastdl.mongodb.org/linux"
arg_pkg_mongosh="https://downloads.mongodb.com/compass"
env_port=27017
env_replSet="rs0"

case "$arch" in
arm64)
	arg_pkg_mongo="${arg_pkg_mongo}/mongodb-linux-aarch64-ubuntu2204-${version_mongo}.tgz"
	arg_pkg_mongosh="${arg_pkg_mongosh}/mongosh-${version_mongosh}-linux-arm64.tgz"
	platform="linux/arm64/v8"
	container="${prefix}-mongo-arm64-$version_mongo"
	tag="$prefix-mongo-arm64:$version_mongo"
	;;
x86_64)
	arg_pkg_mongo="${arg_pkg_mongo}/mongodb-linux-x86_64-ubuntu2204-${version_mongo}.tgz"
	arg_pkg_mongosh="${arg_pkg_mongosh}/mongosh-${version_mongosh}-linux-x64.tgz"
	platform="linux/x86_64"
	container="${prefix}-mongo-x86_64-$version_mongo"
	tag="${prefix}-mongo-x86_64:$version_mongo"
	;;
*)
	log_error ">>> Unsupported architecture: $arch."
	exit 1
	;;
esac

case "$1" in
reset)
	container_reset "$container" "$volume"
	;;
rm)
	container_rm "$container" "$volume" "$tag"
	;;
stop)
	container_stop "$container"
	;;
build)
	docker build \
		--build-arg PKG_MONGO="$arg_pkg_mongo" \
		--build-arg PKG_MONGOSH="$arg_pkg_mongosh" \
		--platform $platform \
		--tag $tag \
		--file "./Dockerfile.${arch}" .
	docker volume create "$volume"
	;;
start)
	container_id="$(docker ps -aq --filter name="$container")"
	if [ -n "$container_id" ]; then
		docker start "$container"

	else docker run -d --init \
		-e port="$env_port" \
		-e replSet="$env_replSet" \
		-p "$env_port:$env_port" \
		--platform $platform \
		--mount source="$volume",target=/data/db \
		--name "$container" \
		"$tag"
	fi

	docker logs --follow --tail 15 "$container" &
	wait
	;;
*)
	log_warning ">>> Unknown or missing action."
	log_warning "\$ ./lets build|start|stop|reset|rm"
	;;
esac